name: Getdeck/getdeck-action
description: "A GitHub Action to create Kubernetes cluster infrastructure with Getdeck"
author: vvvityaaa

branding:
  icon: box
  color: green
inputs:
  deck-file-path:
    description: "Path to the Deckfile."
    required: false
    default: "."
  deck-name:
    description: "Name of a Deck to run from the Deckfile."
    required: false
  wait:
    description: "Wait for the Pods of the Deck to become ready"
    required: false
    default: "true"
  timeout:
    description: "Timeout (in seconds) for the Pods of the Deck to become ready; if exceeded the run fails"
    required: false
    default: "120"
runs:
  using: composite
  steps:
    - id: k3d
      shell: bash
      run: "curl -s https://raw.githubusercontent.com/k3d-io/k3d/main/install.sh | bash"
    - id: getdeck
      shell: bash
      run: "curl -sSL https://raw.githubusercontent.com/getdeck/getdeck/main/install.sh | sh -"
    - id: main
      shell: bash
      run: ${{ github.action_path }}/run.sh deploy
      env:
        DECK_FILE_PATH: ${{ inputs.deck-file-path }}
        DECK_NAME: ${{ inputs.deck-name }}
        WAIT: ${{ inputs.wait }}
        TIMEOUT: ${{ inputs.timeout }}
