name: Build infrastructure using getdeck for gefyra demo

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install k3d
      run: |
        curl -s https://raw.githubusercontent.com/k3d-io/k3d/main/install.sh | bash
    - name: Install Getdeck
      run: |
        curl -sSL https://raw.githubusercontent.com/getdeck/getdeck/main/install.sh | sh -
    - uses: Getdeck/getdeck-action@main
      name: Create Infrastructure from Deckfile
      with:
        deck-file-path: https://github.com/gefyrahq/gefyra-demos.git
