name: Build infrastructure using getdeck for django hurricane

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: Getdeck/getdeck-action@main
      name: Create Infrastructure from Deckfile
      with:
        deck-file-path: https://raw.githubusercontent.com/Getdeck/wharf/main/django/deck.yaml
